sudo: true
git:
  depth: 10
branches:
  only:
    - master
notifications:
  email:
    on_success: never
    on_failure: change
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
os: linux
env: LPHP_OS=linux
script: scripts/build_package.sh

language: php
php:
  - 5.6
