sudo: true
git:
  depth: 10
branches:
  only:
    - master
notifications:
  email:
    on_success: never
    on_failure: change
os: osx
before_install:
  # Updating PHP to 5.6
  - curl -s http://php-osx.liip.ch/install.sh | bash -s 5.6
  - export PATH=/usr/local/php5/bin:$PATH
  - php --version

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
