### Project specific config ###
language: php
matrix:
  include:
    - os: linux
      php: '5.6'

    - os: linux
      php: '7.0'

    - os: linux
      php: '7.1'
      env:
        - ATOM_CHANNEL=beta

after_failure:
  - php --syntax-check --define display_errors=On --define log_errors=Off ./spec/files/good.php
  - php --syntax-check --define display_errors=On --define log_errors=Off ./spec/files/bad.php

before_script:
  - php --version

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^greenkeeper/.*$/

git:
  depth: 10

sudo: false

dist: trusty

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
