### Project specific config ###
language: php
matrix:
  include:
    - os: linux
      php: '5.6'

    - os: linux
      php: '7.0'

    - os: linux
      php: '7.0'
      env:
        - ATOM_CHANNEL=beta

    - os: osx
      language: generic
      install:
        # Updating PHP to 5.6.x
        - curl -s http://php-osx.liip.ch/install.sh | bash -s 5.6
        - export PATH=/usr/local/php5/bin:$PATH

    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - ATOM_CHANNEL=beta
      install:
        # Updating PHP to 7.0.x
        - curl -s http://php-osx.liip.ch/install.sh | bash -s 7.0
        - export PATH=/usr/local/php5/bin:$PATH

after_failure:
  - php --syntax-check --define display_errors=On --define log_errors=Off ./spec/files/good.php
  - php --syntax-check --define display_errors=On --define log_errors=Off ./spec/files/bad.php

before_script:
  - php --version

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
