sudo: true
git:
  depth: 10
branches:
  only:
    - master
notifications:
  email:
    on_success: never
    on_failure: change
matrix:
  include:
    - os: linux
      env: LPHP_OS=linux
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      language: php
    - os: osx
      env: LPHP_OS=osx

script: scripts/build_package.sh
